valor1 = input()
valor2 = input()
valor3 = input()
print(valor1, end="")
print(valor2, end="")
print(valor3)
print(valor2, end="")
print(valor3, end="")
print(valor1)
print(valor3, end="")
print(valor1, end="")
print(valor2)
print(valor1[0:10], end="")
print(valor2[0:10], end="")
print(valor3[0:10])