a = (int)(15)
b = (int)(a/2)
c = (float)(15.456)
d = (float)(c/7)
print("Valores de b:")
print("-------------")
print("1) b = {}".format(b))
print("2) b = {:21.0f}".format(b))
print("3) b = 00000000000000000000{}".format(b))
print("4) b = {}{:<20}".format(b," "))
print("5) b = {}%".format(b))
print()
print("Valores de d:")
print("-------------")
print("1) d = {:.6f}".format(d))
print("2) d = {:.0f}".format(d))
print("3) d = {:.1f}".format(d))
print("4) d = {:.2f}".format(d))
print("5) d = {:.3f}".format(d))
print("6) d = {:20.3f}".format(d))
print("7) d = {:020.3f}".format(d))
print("8) d = {:.3f}{:<20}".format(d, " "))
print("9) d = {:.2f}%".format(d))
